export { HomePage } from './HomePage'
export { FeaturesPage } from './FeaturesPage'
export { PricingPage } from './PricingPage'
export { ContactPage } from './ContactPage'
export { AdoptionPage } from './AdoptionPage'
