import { cosineSimilarity, embed, embedMany } from 'ai'
import { openai } from '@ai-sdk/openai'

/** 50 test documents covering diverse product topics */
const TEST_DOCUMENTS = [
  'Tour Kit is a headless onboarding library for React applications.',
  'The useTour hook manages tour lifecycle including start, stop, and navigation.',
  'Steps can be configured with custom content, placement, and spotlighting.',
  'The TourProvider component wraps your app and manages tour state.',
  'Hints are small beacons that draw attention to UI elements.',
  'Checklists help users track onboarding progress with task dependencies.',
  'The analytics package supports plugin-based event tracking.',
  'Announcements can be displayed as modals, banners, toasts, or slideouts.',
  'The media package supports YouTube, Vimeo, Loom, and Wistia embeds.',
  'Scheduling allows time-based content delivery with timezone support.',
  'Installation requires pnpm add @tour-kit/core @tour-kit/react.',
  'TypeScript strict mode is enabled across all packages.',
  'Bundle size budgets: core < 8KB, react < 12KB gzipped.',
  'WCAG 2.1 AA accessibility compliance is a core requirement.',
  'The spotlight effect highlights target elements during tours.',
  'Keyboard navigation supports Escape to close and Tab for focus.',
  'CSS custom properties allow theming without Tailwind CSS.',
  'The headless API exposes render props for custom component styling.',
  'Tour branching allows conditional step navigation based on user choices.',
  'Persistence stores tour progress in localStorage or custom adapters.',
  'The useStep hook provides current step data and navigation methods.',
  'Focus trapping keeps keyboard focus within the active tour step.',
  'Animations use CSS transitions respecting prefers-reduced-motion.',
  'The createTour utility validates and normalizes tour configuration.',
  'Multiple tours can be registered and triggered by ID.',
  'Tour events include onStart, onComplete, onStepChange, and onDismiss.',
  'The overlay component dims the background during active tours.',
  'Progress indicators show completion percentage during tours.',
  'The close button component handles tour dismissal with cleanup.',
  'Route change detection pauses tours during navigation.',
  'The TourCard component renders step content with navigation controls.',
  'Floating UI handles tooltip positioning and collision detection.',
  'The throttle utility prevents excessive event handler calls.',
  'Changeset-based versioning manages package releases.',
  'The monorepo uses Turborepo for build orchestration.',
  'ESM and CJS dual format builds are generated by tsup.',
  'React 18 and 19 are both supported via peer dependencies.',
  'The adoption package tracks feature usage and triggers nudges.',
  'Rate limiting prevents API abuse in server-side handlers.',
  'The system prompt is assembled from three layers: defaults, config, custom.',
  'CAG (context-augmented generation) stuffs all docs into the system prompt.',
  'RAG retrieval uses cosine similarity to find relevant document chunks.',
  'Vector stores can be in-memory or external (Pinecone, pgvector).',
  'The markdown renderer produces React elements without dangerouslySetInnerHTML.',
  'Suggestion chips provide quick follow-up questions after AI responses.',
  'Chat persistence survives page reload via localStorage adapter.',
  'The beforeSend hook allows filtering user messages before processing.',
  'Error boundaries catch and display rendering failures gracefully.',
  'The AI chat panel supports slideout, popover, and inline display modes.',
  'Token streaming uses Server-Sent Events for real-time delivery.',
]

/**
 * Run the vector search spike.
 * Usage: npx tsx packages/ai/src/__spikes__/vector-spike.ts
 * Requires: OPENAI_API_KEY environment variable
 */
export async function runVectorSearchSpike(query: string) {
  const embeddingModel = openai.embedding('text-embedding-3-small')

  console.log(`[vector-spike] Embedding ${TEST_DOCUMENTS.length} documents...`)
  const startEmbed = performance.now()

  const { embeddings } = await embedMany({
    model: embeddingModel,
    values: TEST_DOCUMENTS,
  })

  const embedTime = performance.now() - startEmbed
  console.log(`[vector-spike] Embedding took ${embedTime.toFixed(0)}ms`)

  // Build in-memory store
  const db = TEST_DOCUMENTS.map((doc, i) => ({
    document: doc,
    embedding: embeddings[i],
  }))

  console.log(`[vector-spike] Searching for: "${query}"`)
  const startSearch = performance.now()

  const { embedding: queryEmbedding } = await embed({
    model: embeddingModel,
    value: query,
  })

  const results = db
    .map((item) => ({
      document: item.document,
      similarity: cosineSimilarity(queryEmbedding, item.embedding),
    }))
    .sort((a, b) => b.similarity - a.similarity)
    .slice(0, 3)

  const searchTime = performance.now() - startSearch
  console.log(`[vector-spike] Search took ${searchTime.toFixed(0)}ms`)

  console.log('\n[vector-spike] Top 3 results:')
  results.forEach((r, i) => {
    console.log(`  ${i + 1}. [${r.similarity.toFixed(4)}] ${r.document}`)
  })

  return { results, searchTime, embedTime }
}

// Run if executed directly
const query = process.argv[2] || 'How do I install the library?'
runVectorSearchSpike(query).catch(console.error)
