import { SITE_LAUNCH_FALLBACK, getGitLastModified } from '@/lib/git-dates'
import { baseOptions } from '@/lib/layout.shared'
import {
  BreadcrumbJsonLd,
  DEFAULT_SPEAKABLE_SELECTORS,
  SpeakableJsonLd,
} from '@/lib/structured-data'
import { HomeLayout } from 'fumadocs-ui/layouts/home'
import type { Metadata } from 'next'
import Link from 'next/link'
import path from 'node:path'

const TITLE = 'How We Test'
const DESCRIPTION =
  'The methodology behind userTourKit benchmarks, bundle-size claims, accessibility scores, and comparison data — how measurements are produced, which versions are tested, and how to reproduce them.'

export const metadata: Metadata = {
  title: `${TITLE} — userTourKit`,
  description: DESCRIPTION,
  alternates: { canonical: '/how-we-test' },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: 'article',
    url: '/how-we-test',
    images: [`/api/og?title=${encodeURIComponent('How We Test')}&category=METHODOLOGY`],
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    images: [`/api/og?title=${encodeURIComponent('How We Test')}&category=METHODOLOGY`],
  },
}

export default function HowWeTestPage() {
  const pageFile = path.join(process.cwd(), 'app/how-we-test/page.tsx')
  const lastUpdated = getGitLastModified(pageFile)
  const lastUpdatedIso = Number.isNaN(lastUpdated.getTime())
    ? SITE_LAUNCH_FALLBACK
    : lastUpdated.toISOString()
  const lastUpdatedDisplay = new Date(lastUpdatedIso).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })

  return (
    <HomeLayout {...baseOptions()}>
      <BreadcrumbJsonLd
        items={[
          { name: 'Home', url: '/' },
          { name: 'How We Test', url: '/how-we-test' },
        ]}
      />
      <SpeakableJsonLd url="/how-we-test" cssSelectors={[...DEFAULT_SPEAKABLE_SELECTORS]} />
      <main
        id="main-content"
        className="mx-auto w-full max-w-[820px] px-6 py-16 sm:px-8 sm:py-20 lg:px-12"
      >
        <header className="mb-10">
          <h1
            data-speakable="headline"
            className="mb-4 text-3xl font-bold tracking-[-0.02em] text-fd-foreground sm:text-4xl"
          >
            {TITLE}
          </h1>
          <p
            data-speakable="summary"
            className="text-[16px] leading-relaxed text-fd-muted-foreground"
          >
            {DESCRIPTION}
          </p>
          <p className="mt-3 text-[13px] text-fd-muted-foreground">
            Last updated <time dateTime={lastUpdatedIso}>{lastUpdatedDisplay}</time>
          </p>
        </header>

        <article className="prose prose-neutral dark:prose-invert max-w-none">
          <h2>Testing philosophy</h2>
          <p>
            Every technical claim on this site is either (a) generated by running the current
            release in CI or (b) cited from a primary source that the reader can verify. When a
            measurement would require us to re-run a benchmark, we publish the methodology — not
            just the number — so it can be reproduced. If a claim cannot be verified, it is not
            published.
          </p>

          <h2 id="automated">Automated quality gates (CI)</h2>
          <p>
            Every pull request to{' '}
            <a
              href="https://github.com/DomiDex/tour-kit"
              target="_blank"
              rel="noopener noreferrer"
            >
              github.com/DomiDex/tour-kit
            </a>{' '}
            passes the following before merge:
          </p>
          <ul>
            <li>
              <strong>TypeScript strict mode</strong> across all packages via{' '}
              <code>pnpm typecheck</code>. No implicit <code>any</code>, no unchecked indexed
              access.
            </li>
            <li>
              <strong>Unit and integration tests</strong> via Vitest and{' '}
              <code>@testing-library/react</code>. Target coverage is &gt;80% meaningful coverage on
              shipped packages.
            </li>
            <li>
              <strong>Production build</strong> via tsup for ESM + CJS bundles with TypeScript
              declarations. If the build fails, the PR cannot merge.
            </li>
            <li>
              <strong>Bundle-size budgets</strong> are defined per package:{' '}
              <code>@tour-kit/core</code> &lt; 8 KB gzipped, <code>@tour-kit/react</code> &lt; 12
              KB, <code>@tour-kit/hints</code> &lt; 5 KB. When a PR pushes a bundle over budget, we
              either reduce scope or justify the increase in the changeset.
            </li>
            <li>
              <strong>Linting</strong> via Biome for consistency and basic correctness
              (unused vars, obvious anti-patterns).
            </li>
          </ul>

          <h2 id="manual">Manual verification</h2>
          <ul>
            <li>
              <strong>Browser smoke-test.</strong> New components are exercised in the docs app
              against the current latest Chromium, Firefox, and Safari before release. Keyboard
              navigation and screen-reader labels are verified for every interactive primitive.
            </li>
            <li>
              <strong>Accessibility.</strong> We target WCAG 2.1 AA. Components are spot-checked
              with axe-core and a screen reader (VoiceOver / NVDA). Lighthouse Accessibility score
              of 100 on the docs site is a release gate.
            </li>
            <li>
              <strong>Documentation parity.</strong> Code samples in MDX are pasted into a blank
              Next.js 15 project and run at least once per quarter to catch drift.
            </li>
          </ul>

          <h2 id="bundle-size">Bundle-size methodology</h2>
          <p>
            Reported bundle sizes are <strong>gzipped</strong> measurements of the production tsup
            build, inspected from{' '}
            <a href="https://bundlephobia.com/" target="_blank" rel="noopener noreferrer">
              bundlephobia.com
            </a>{' '}
            or measured locally with <code>size-limit</code> against the package&apos;s exported
            entry points. Tree-shaken sizes (subset imports) are labeled separately. When we
            compare competitor bundles we use the same tooling on the same day, against each
            package&apos;s published npm version — never a stale figure from a blog post. The{' '}
            <Link href="/benchmarks/bundle-size">live bundle-size benchmark</Link> publishes the
            raw numbers with the measurement date and source links.
          </p>

          <h2 id="benchmarks">Benchmark methodology</h2>
          <p>
            Performance comparisons (render time, time-to-first-step, memory usage) use a
            deterministic harness run on a reference machine with fixed CPU throttling in a
            headless Chromium session. Each scenario runs ≥10 iterations; we report the{' '}
            <strong>median and p95</strong>, not the single fastest run. The harness source and
            raw results are published alongside every benchmark so they can be rerun.
          </p>
          <p>
            Until published harness URLs land, benchmark figures are labeled{' '}
            <em>preliminary</em> and the underlying data file is linked directly from the article.
          </p>

          <h2 id="comparisons">Comparison article methodology</h2>
          <p>
            For articles that compare userTourKit against other libraries or SaaS tools:
          </p>
          <ul>
            <li>
              We read the <strong>current</strong> official docs of the compared tool — version and
              access date are footnoted in the article.
            </li>
            <li>
              Feature matrices map each row to a linkable evidence URL on the competitor&apos;s
              site, repo, or pricing page.
            </li>
            <li>
              Subjective claims (&quot;easier to style&quot;, &quot;better DX&quot;) are marked as
              opinion and justified with a concrete example.
            </li>
            <li>
              Our own product is bracketed inside a labeled &quot;<em>From the authors</em>&quot;
              note so readers can weigh the commercial bias.
            </li>
          </ul>

          <h2 id="reproducibility">Reproducibility</h2>
          <p>
            Everything we publish should be reproducible by a reader:
          </p>
          <ul>
            <li>
              The full source of the library and the docs site lives in the{' '}
              <a
                href="https://github.com/DomiDex/tour-kit"
                target="_blank"
                rel="noopener noreferrer"
              >
                public repository
              </a>
              .
            </li>
            <li>
              Build commands (<code>pnpm build</code>, <code>pnpm typecheck</code>,{' '}
              <code>pnpm test</code>) are documented in the root <code>CLAUDE.md</code> and
              package READMEs.
            </li>
            <li>
              Benchmark data files (when published) are committed as JSON alongside the article
              MDX.
            </li>
          </ul>

          <h2>Related</h2>
          <p>
            See the <Link href="/editorial-policy">editorial policy</Link> for how content is
            sourced, reviewed, corrected, and disclosed.
          </p>
        </article>
      </main>
    </HomeLayout>
  )
}
